title: "DapTap Status "
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: ""
  systems:
    - name: "Game Panel "
    - name: Game Servers
    - name: "Website "
    - name: VPS
    - name: APIs
    - name: Main servers
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " UTC"
  logo: ""
  description_header: "DapTap server want to make sure you and us can keep up to
    date on issues with our service "
  copyrightHolder: DapTap
  eventsPerPage: 10
  iconType: image/png
  icon: /images/clearstatus.png
  description_footer: ""
